apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
      - name: web-server
        image: 316412051370.dkr.ecr.us-east-1.amazonaws.com/watchwolf-dev-terraform-ecr-repo:web-server
        imagePullPolicy: Always
        ports:
        - containerPort: 80