apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-pod
    app.kubernetes.io/name: backend-pod
  name: backend-pod
  namespace: app
spec:
  ports:
  - name: http
    nodePort: 30162
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: backend-pod
  type: NodePort