apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-pod
    app.kubernetes.io/name: frontend-pod
  name: frontend-pod
  namespace: app
spec:
  ports:
  - name: http
    nodePort: 30163
    port: 80
    protocol: TCP
    targetPort: 4200
  selector:
    app: frontend-pod
  type: NodePort